# Generated by Django 5.2.15 on 2026-06-28 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['business', 'is_deleted'], name='expenses_busines_cac680_idx'),
        ),
        migrations.AddIndex(
            model_name='jobcard',
            index=models.Index(fields=['business', 'intake_date'], name='job_cards_busines_0ac381_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['business', 'payment_method'], name='payments_busines_6479d3_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['business', 'created_by'], name='sales_busines_e0ae6d_idx'),
        ),
    ]
