# Generated by Django 5.2.15 on 2026-06-30 10:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('room_number', models.CharField(max_length=20)),
                ('room_type', models.CharField(choices=[('single', 'Single'), ('double', 'Double'), ('twin', 'Twin'), ('suite', 'Suite'), ('family', 'Family'), ('deluxe', 'Deluxe')], default='double', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('capacity', models.PositiveIntegerField(default=2)),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=15)),
                ('status', models.CharField(choices=[('available', 'Available'), ('occupied', 'Occupied'), ('maintenance', 'Under Maintenance')], default='available', max_length=20)),
                ('floor', models.CharField(blank=True, max_length=10, null=True)),
                ('amenities', models.CharField(blank=True, help_text='Comma-separated list', max_length=500, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='core.business')),
            ],
            options={
                'db_table': 'hotel_rooms',
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('booking_number', models.CharField(max_length=20, unique=True)),
                ('guest_name', models.CharField(max_length=150)),
                ('guest_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('guest_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('check_in_date', models.DateField()),
                ('check_out_date', models.DateField()),
                ('nights', models.PositiveIntegerField(default=1)),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('balance_due', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('payment_status', models.CharField(choices=[('unpaid', 'Unpaid'), ('partial', 'Partial'), ('paid', 'Paid')], default='unpaid', max_length=20)),
                ('payment_method', models.CharField(blank=True, choices=[('cash', 'Cash'), ('transfer', 'Transfer'), ('pos', 'POS')], max_length=20, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('checked_in', 'Checked In'), ('checked_out', 'Checked Out'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('checked_in_at', models.DateTimeField(blank=True, null=True)),
                ('checked_out_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='core.business')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_bookings', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='core.room')),
            ],
            options={
                'db_table': 'hotel_bookings',
            },
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['business', 'status'], name='hotel_rooms_busines_5db30d_idx'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['business', 'room_type'], name='hotel_rooms_busines_f692ad_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='room',
            unique_together={('business', 'room_number')},
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['business', 'status'], name='hotel_booki_busines_e6e46c_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['business', 'payment_status'], name='hotel_booki_busines_140830_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['room', 'check_in_date', 'check_out_date'], name='hotel_booki_room_id_8f010d_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['business', 'check_in_date'], name='hotel_booki_busines_2727df_idx'),
        ),
    ]
