# Generated by Codex on 2026-07-02

import django.db.models.deletion
import uuid
from django.db import migrations, models


DEFAULT_PRODUCT_CATEGORIES = {
    'general_trade': [
        'Foodstuff', 'Beverages', 'Snacks', 'Toiletries', 'Household Items',
        'Baby Products', 'Cleaning Supplies', 'Frozen Foods', 'Stationery',
        'Health & Personal Care',
    ],
    'fashion': [
        "Men's Wear", "Women's Wear", "Children's Wear", 'Shoes', 'Bags',
        'Accessories', 'Fabrics', 'Native Wear', 'Corporate Wear', 'Sportswear',
    ],
    'electronics': [
        'Phones', 'Laptops', 'Tablets', 'TVs', 'Audio Devices', 'Chargers',
        'Cables', 'Accessories', 'Gaming Devices', 'Used / Refurbished',
    ],
    'food': [
        'Grains', 'Oils', 'Spices', 'Fresh Produce', 'Frozen Foods', 'Dairy',
        'Meat & Fish', 'Packaged Foods', 'Drinks', 'Household Essentials',
    ],
    'pharmacy': [
        'Prescription Drugs', 'Over-the-Counter Drugs', 'Supplements', 'First Aid',
        'Medical Devices', 'Skincare', 'Baby Care', 'Hygiene Products',
        'Lab / Diagnostic Items', 'Controlled Drugs',
    ],
    'building_materials': [
        'Cement', 'Iron Rods', 'Roofing Sheets', 'Plumbing Materials',
        'Electrical Fittings', 'Paints', 'Tiles', 'Tools', 'Timber & Boards',
        'Sand & Aggregates',
    ],
    'stationery': [
        'Exercise Books', 'Textbooks', 'Writing Materials', 'Office Supplies',
        'Art Supplies', 'School Bags', 'Files & Folders', 'Printing Supplies',
        'Uniform Accessories',
    ],
    'technical_services': [
        'Spare Parts', 'Screens', 'Batteries', 'Charging Ports', 'Speakers & Mics',
        'Tools', 'Accessories', 'Software Services', 'Diagnostic Fees', 'Labour',
    ],
    'hotel': [
        'Rooms', 'Food & Drinks', 'Mini Bar Items', 'Laundry', 'Event Hall',
        'Add-on Services', 'Tour Packages', 'Housekeeping Supplies',
    ],
}


def seed_product_categories(apps, schema_editor):
    Business = apps.get_model('core', 'Business')
    Module = apps.get_model('core', 'Module')
    ProductCategory = apps.get_model('core', 'ProductCategory')

    modules = {module.code: module for module in Module.objects.filter(is_active=True)}
    for business in Business.objects.all():
        for module_code, names in DEFAULT_PRODUCT_CATEGORIES.items():
            module = modules.get(module_code)
            if not module:
                continue
            for name in names:
                ProductCategory.objects.get_or_create(
                    business=business,
                    module=module,
                    name=name,
                    defaults={'is_custom': False},
                )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_service_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('is_custom', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_categories', to='core.business')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_categories', to='core.module')),
            ],
            options={
                'db_table': 'product_categories',
                'ordering': ['module__sort_order', 'name'],
                'unique_together': {('business', 'module', 'name')},
            },
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='core.productcategory'),
        ),
        migrations.AddIndex(
            model_name='productcategory',
            index=models.Index(fields=['business', 'module'], name='product_cat_busines_8defb8_idx'),
        ),
        migrations.AddIndex(
            model_name='productcategory',
            index=models.Index(fields=['business', 'is_active'], name='product_cat_busines_6e8f57_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['business', 'category'], name='products_busines_f3c1c1_idx'),
        ),
        migrations.RunPython(seed_product_categories, migrations.RunPython.noop),
    ]