# Generated by Django 5.2.15 on 2026-09-28 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_passwordresettoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcard',
            name='pickup_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
