# Generated by Django 5.2.15 on 2026-09-28 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_backfill_daily_summary_privilege'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='jobcard',
            name='job_number',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='sale',
            name='sale_number',
            field=models.CharField(max_length=50),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(fields=('business', 'booking_number'), name='unique_booking_number_per_business'),
        ),
        migrations.AddConstraint(
            model_name='jobcard',
            constraint=models.UniqueConstraint(fields=('business', 'job_number'), name='unique_job_number_per_business'),
        ),
        migrations.AddConstraint(
            model_name='sale',
            constraint=models.UniqueConstraint(fields=('business', 'sale_number'), name='unique_sale_number_per_business'),
        ),
    ]
