# Generated by Django 5.2.15 on 2026-09-29 05:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_booking_booking_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobcard',
            name='intake_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
