# Generated by Django 5.2.15 on 2026-09-29 05:11

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_jobcard_intake_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='new_values',
            field=models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='old_values',
            field=models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True),
        ),
    ]
