# Generated by Django 5.2.15 on 2026-09-29 19:18

import django.core.serializers.json
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_auditlog_new_values_alter_auditlog_old_values'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdempotencyRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=100)),
                ('method', models.CharField(max_length=10)),
                ('path', models.CharField(max_length=255)),
                ('status_code', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('response_body', models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idempotency_records', to='core.business')),
            ],
            options={
                'db_table': 'idempotency_records',
                'indexes': [models.Index(fields=['created_at'], name='idempotency_created_3fb3ea_idx')],
                'constraints': [models.UniqueConstraint(fields=('business', 'key'), name='unique_idempotency_key_per_business')],
            },
        ),
    ]
